### PR TITLE
assorted attempts to fix wasm stutter

### PR DESCRIPTION
**Pull request by bcspragu**
Mostly, just replace my janky `sleep` approach with [the native one from `tokio_stream`](https://docs.rs/tokio-stream/latest/tokio_stream/trait.StreamExt.html#method.throttle)

Also, remove the `KeepAlive` because we know we're sending data consistently ~10 times a second, no need for extra pings

Should fix https://github.com/gregsadetsky/rapidriteros/issues/11

### CODE REVIEW

**Review by gregsadetsky — APPROVED** [review]

**Comment by gregsadetsky** [comment]
oooooooooooooh it looks great locally here @bcspragu !!!!!!!!!

it's all pushed and deployed to the riter - I should be in the hub next week at some point to take a look!

congrats and thanks again!

**Comment by bcspragu** [comment]
Woot woot! And likewise, thanks for all the help with debugging and deploying and physically existing in NYC. Can't wait to see it and start developing shiny new animations for it

**Comment by gregsadetsky** [comment]
............................ are you going to make a rust compiler in wasm to compile stuff to wasm

or like what's the gameplan haha

rust riter??????

so so curious ahha

THANKS!!

**Comment by bcspragu** [comment]
> are you going to make a rust compiler in wasm to compile stuff to wasm

:exploding_head: 

My plans are much more mundane: port existing algos I made for [Abound.art](https://abound.art/) (but are not currently on display there) to the riter. The one I have in mind is already written in Rust and should be straightforward ([working on it here](https://git.sr.ht/~bsprague/recurse/tree/main/item/rapidriter/rediff/src/lib.rs)), but I'll encourage folks to write things in any WASM-compiling language they want ([Go](https://go.dev/wiki/WebAssembly)! [Zig](https://ziglang.org/documentation/master/#WebAssembly)! [All these other languages maybe](https://github.com/appcypher/awesome-wasm-langs!))

**Pull request merged**
